# Generated by Django 6.0.1 on 2026-01-15 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код продукции')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('shelf_life_days', models.PositiveIntegerField(verbose_name='Срок годности (дни)')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Номер партии')),
                ('weight_kg', models.FloatField(verbose_name='Вес партии (кг)')),
                ('production_date', models.DateField(verbose_name='Дата производства')),
                ('reception_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата приёмки')),
                ('expiration_date', models.DateField(verbose_name='Срок годности')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='warehouse_app.nomenclature')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('reception', 'Приёмка')], default='reception', max_length=50, verbose_name='Тип операции')),
                ('operation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции')),
                ('quantity', models.FloatField(verbose_name='Количество (кг)')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечание')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='warehouse_app.productbatch')),
            ],
        ),
    ]
