# Generated by Django 6.0.1 on 2026-01-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenclature',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='productbatch',
            options={'verbose_name': 'Партия продукции', 'verbose_name_plural': 'Партии продукции'},
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight_kg', models.FloatField(default=0, verbose_name='Текущий остаток (кг)')),
                ('nomenclature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_item', to='warehouse_app.nomenclature')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
    ]
