# Generated by Django 6.0.1 on 2026-01-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0002_alter_nomenclature_options_alter_operation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbatch',
            options={},
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='reception_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата приёмки'),
        ),
    ]
