# Generated by Django 6.0.1 on 2026-01-16 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0003_alter_productbatch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-operation_date'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='productbatch',
            options={'verbose_name': 'Партия товара', 'verbose_name_plural': 'Партии товара'},
        ),
        migrations.AddField(
            model_name='operation',
            name='document',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='operation',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина списания'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='warehouse_app.productbatch', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('reception', 'Приёмка'), ('deduction', 'Списание')], default='reception', max_length=50, verbose_name='Тип операции'),
        ),
    ]
