# Generated by Django 6.0.1 on 2026-01-23 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0004_alter_operation_options_alter_productbatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='nomenclature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='warehouse_app.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='warehouse_app.nomenclature'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='nomenclature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_item', to='warehouse_app.nomenclature'),
        ),
    ]
