# Generated by Django 6.0.1 on 2026-01-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0005_operation_nomenclature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbatch',
            old_name='weight_kg',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='current_weight_kg',
            new_name='current_quantity',
        ),
    ]
