# Generated by Django 6.0.1 on 2026-01-24 10:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0006_rename_weight_kg_productbatch_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='current_quantity',
            field=models.FloatField(default=0, verbose_name='Текущий остаток'),
        ),
        migrations.CreateModel(
            name='LiveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Текущий остаток')),
                ('product_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_batch', to='warehouse_app.productbatch')),
            ],
            options={
                'verbose_name': 'Активная партия',
                'verbose_name_plural': 'Активные партии',
            },
        ),
    ]
